package com.will.exercisedata.enums;

public enum ExerciseName {

  // CHEST
  FLAT_BENCH_PRESS_DUMBBELL,
  FLAT_BENCH_PRESS_BARBELL,
  MACHINE_CHEST_FLY,
  CABLE_CHEST_FLY,
  DUMBBELL_CHEST_FLY,
  CONVERGING_CHEST_PRESS,
  INCLINE_DUMBBELL_PRESS,
  INCLINE_BENCH_PRESS,
  INCLINE_SMITH_MACHINE_PRESS,
  CHEST_DIPS,

  // LATERAL DELTS
  UPRIGHT_ROWS_DUMBBELLS,
  UPRIGHT_ROWS_BARBELL,
  UPRIGHT_ROWS_SMITH_MACHINE,
  UPRIGHT_ROWS_CABLE,
  SUPER_ROM_LATERAL_RAISES,
  CABLE_LATERAL_RAISES,
  CABLE_FACE_PULLS,

  // OVERHEAD PRESS
  SEATED_SHOULDER_PRESS,

  // REAR DELTS
  REAR_DELTOID_FLY_MACHINE,

  // BACK
  BENT_OVER_ROWS,
  LAT_PULL_DOWNS,
  ASSISTED_PULL_UPS,
  DIVERGING_ROWS,

  // TRICEPS
  SKULL_CRUSHERS,
  CABLE_PUSH_DOWNS,
  TRICEP_DIPS,

  // BICEPS
  BARBELL_BICEP_CURLS,
  HAMMER_CURLS,
  CABLE_BICEP_CURLS,

  // QUADS
  SQUAT,
  LEG_PRESS,
  LEG_EXTENSION,

  // HAMSTRING
  STIFF_LEGGED_DEADLIFT,
  HAMSTRING_CURL,

  // CALVES
  STANDING_CALF_RAISE,
  SEATED_CALF_RAISE,

  // ABS
  LEG_LIFTS,
  CRUNCH_MACHINE

}

